[project]
name = 'apitofsim'
version = '0.0.15'
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "ase>=3.27.0",
  "click>=8.2.0",
  "duckdb>=1.4.2",
  "numpy",
  "orjson>=3.11.4",
  "pandas",
  "pint>=0.25.1",
  "progress-table>=3.2.2",
  "pyarrow>=23.0.0",
  "questionary>=2.1.1",
  "tomlkit>=0.14.0",
  "tomlkit-extras>=0.2.0",
]

[build-system]
build-backend = 'mesonpy'
requires = ["meson-python", "meson >= 1.10.0"]

[project.optional-dependencies]
reflink = ["reflink>=0.2.2"]
plot = [
    "matplotlib>=3.10.7",
    "graphviz>=0.21",
    "holoviews>=1.21.0",
    "textalloc>=1.2.3",
    "seaborn>=0.13.2",
]
notebooks = ["marimo"]

[project.scripts]
apitofsim = "apitofsim.cli:cli"

[dependency-groups]
dev = [
  "meson-python>=0.18.0",
  "pip>=25.2",
  "basedpyright",
  "ruff>=0.15.2",
  "pytest>=9.0.2",
]
docs = [
  "mkdocs-click>=0.9.0",
  "mkdocs-material>=9.7.0",
  "mkdocstrings>=1.0.0",
  "mkdocstrings-python>=2.0.1",
  "mkdocs < 2"
]
notebooks = ["scipy>=1.16.3", "sympy>=1.14.0", "marimo[sql]", "polars[pyarrow]"]

[tool.ruff]
extend-exclude = ["*.mo.py"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.meson-python]
limited-api = true

[tool.meson-python.args]
install = ['--skip-subprojects']
setup = ['-Dpython=enabled']

[tool.cibuildwheel]
manylinux-x86_64-image = "quay.io/pypa/manylinux_2_34_x86_64:latest"
build = "cp313-*"
skip = "*-manylinux_i686 cp3??t-* *-musllinux_*"
archs = ["auto64"]
test-command = "python -c \"import apitofsim; assert apitofsim.precompute_mesh(100.0, 1.0, quantities_strict=False).size == 100\""

[tool.cibuildwheel.linux]
before-build = "bash ci/setup_linux.sh"
config-settings = { setup-args = "--native-file=../meson/pkg/clangwheel.ini" }
repair-wheel-command = [
  "auditwheel repair --disable-isa-ext-check -w {dest_dir} {wheel}",
  "auditwheel show {dest_dir}/*.whl",
  "pipx run abi3audit --strict --report {wheel} --assume-minimum-abi3 3.12",
]

[tool.cibuildwheel.macos]
before-all = "bash {package}/ci/setup_macos.sh"
environment = { CMAKE_PREFIX_PATH = "/tmp/apitofsim-oneapi-tbb" }

[tool.cibuildwheel.windows]
before-all = 'pwsh -NoProfile -File "{package}\ci\setup_windows.ps1"'
before-build = "pip install delvewheel"
config-settings = { setup-args = "--native-file=..\\meson\\pkg\\windowswheel.ini" }
environment = { CMAKE_PREFIX_PATH = 'C:\apitofsim-oneapi-tbb\oneapi-tbb-2023.1.0' }
repair-wheel-command = 'delvewheel repair --add-path C:\apitofsim-oneapi-tbb\oneapi-tbb-2023.1.0\redist\intel64\vc14 -w {dest_dir} {wheel}'

[[tool.cibuildwheel.overrides]]
select = "*-x86_64"
inherit.environment = "append"
environment.CXXFLAGS = "-march=x86-64-v3"

[tool.pyright]
reportConstantRedefinition = false
reportImportCycles = false
failOnWarnings = false

[tool.uv]
no-build-isolation-package = ["apitofsim"]
