fs = import('fs')
raw_test_data_files = [
   fs.copyfile('1ABisopooh1brd1w-1100001000_1_129_en.dat'),
   fs.copyfile('1ABisopooh1brd1w-1100001000_1_129_rot.dat'),
   fs.copyfile('1ABisopooh1brd1w-1100001000_1_129_vib.dat'),
   fs.copyfile('1ABisopooh1w-1010000_7_18-str7-str7_en.dat'),
   fs.copyfile('1ABisopooh1w-1010000_7_18-str7-str7_rot.dat'),
   fs.copyfile('1ABisopooh1w-1010000_7_18-str7-str7_vib.dat'),
   fs.copyfile('1brd-1000_1_0_en.dat'),
   fs.copyfile('1brd-1000_1_0_rot.dat'),
   fs.copyfile('1brd-1000_1_0_vib.dat'),
   fs.copyfile('config.in'),
]
