fs = import('fs')
besel_files += [
   fs.copyfile('1A_1SA.log'),
   fs.copyfile('1A_1SA.out'),
   fs.copyfile('1A_1SA.xyz'),
   fs.copyfile('1A_2SA.log'),
   fs.copyfile('1A_2SA.out'),
   fs.copyfile('1A_2SA.xyz'),
   fs.copyfile('1SA.log'),
   fs.copyfile('1SA.out'),
   fs.copyfile('1SA.xyz'),
   fs.copyfile('2SA.log'),
   fs.copyfile('2SA.out'),
   fs.copyfile('2SA.xyz'),
]
