context:
  name: apitofsim
  version: "0.0.1"
  python_min: "3.12"
  build: 0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ..

build:
  # Prioritize builds with a higher microarch level
  number: ${{ build|int + (microarch_level|int) * 100 }}
  script:
    - if: unix
      then: |
        pip install --config-settings=setup-args=--native-file=$SRC_DIR/meson/pkg/clangwheel.ini .
    - if: win
      then: |
        pip install --config-settings=setup-args=--native-file=%SRC_DIR%/meson/pkg/windowswheel.ini .
  python:
    version_independent: true

requirements:
  build:
    - clang
    - clangxx
    - llvm-openmp
    - if: win
      then: clang-cl_win-64
    - if: microarch_level|int > 0
      then: x86_64-microarch-level ==${{ microarch_level }}
  host:
    - python ${{ python_min }}.*
    - python-abi3 ${{ python_min }}.*  
    - pip
    - python-build
    - llvm-openmp
    - meson-python
    - ninja
    - nanobind
    - eigen
  run:
    - python >=${{ python_min }}
    - numpy
    - pandas
    - pint >= 0.25.1

tests:
  - python:
      imports:
        - _${{ name }}
        - ${{ name }}
      python_version: ["${{ python_min ~ '.*' }}"]  

about:
  homepage: https://github.com/VilmaLab/apitofsim
  license: MIT
  license_file:
    - LICENSE
  summary: Simulation of an APi-TOF Mass Spectrometer 
  repository: https://github.com/VilmaLab/apitofsim
