name: Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  # This checks it's possible to build with the default Ubuntu compiler and run C++ tests
  build_test_gcc:
    name: Full build with default compiler then C++ tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          sudo pip install meson

      - name: Build
        run: |
          meson setup --warnlevel 3 --werror build
          meson compile -C build

      - name: Test
        run: |
          meson test --print-errorlogs -C build

  # This compiles with Clang against many LLVM sanitisers (common ones except for memory and thread) and runs the test suite for C++/Python
  build_test_llvm:
    name: Full build with Clang then C++/Python tests under LLVM sanitisers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y clang-tidy-20 clang-format-20 clang-20 lld-20 libomp5-20 libomp-20-dev
          sudo ln -sf /usr/bin/clang-tidy-20 /usr/bin/clang-tidy
          sudo ln -sf /usr/bin/clang-format-20 /usr/bin/clang-format
          sudo ln -sf /usr/bin/clang++-20 /usr/bin/clang++
          sudo ln -sf /usr/bin/lld-20 /usr/bin/lld
          sudo apt-get install -y libc++-20-dev
          sudo pip install meson

      - uses: astral-sh/setup-uv@v7

      - name: Install Python dependencies
        run: |
          uv sync --no-install-project

      - name: Setup/compile with meson
        run: |
          uv run meson setup --native-file=meson/test/manysan.ini build
          uv run meson compile -C build

      - name: Run tests
        run: |
          uv run meson test --print-errorlogs -C build

  # This compiles with the default compiler via uv/meson-python and runs the Python test suite using the -X dev option
  build_test_x_dev:
    name: Full build with default compiler via meson-python then Python tests with -X dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v7

      - name: Install Python dependencies
        run: |
          uv sync

      - name: Run tests
        run: |
          DATA_DIR=$(pwd)/test/data/raw uv run python -X dev -m pytest test/

  # This builds with Clang and runs Valgrind on C++ tests only (slow -- takes around 8 mins at the moment)
  # It may be that this needs to change to manually triggered or run a subset of tests later on
  test_valgrind:
    name: C++ only build with Clang then C++ tests under Valgrind
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson clang-tidy-20 clang-format-20 clang-20 lld-20 libomp5-20 libomp-20-dev valgrind
          sudo ln -sf /usr/bin/clang-tidy-20 /usr/bin/clang-tidy
          sudo ln -sf /usr/bin/clang-format-20 /usr/bin/clang-format
          sudo ln -sf /usr/bin/clang++-20 /usr/bin/clang++
          sudo ln -sf /usr/bin/lld-20 /usr/bin/lld

      - name: Setup meson
        run: |
          meson setup --native-file=meson/test/valgrind.ini build

      - name: Test with valgrind
        run: |
          meson test --print-errorlogs --wrapper=valgrind -C build
