name: Build Python wheels

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_linux_wheel:
    name: Build wheels on Linux
    uses: ./.github/workflows/build-wheel.yml
    with:
      os: ubuntu-latest

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-15]
    uses: ./.github/workflows/build-wheel.yml
    with:
      os: ${{ matrix.os }}

  docs:
    name: Docs
    needs: build_linux_wheel
    uses: ./.github/workflows/docs.yml
